library(shiny)

fluidPage(
  includeCSS("www/styles.css"),
  titlePanel('ScreenTime Tracker', windowTitle = 'ScreenTime Tracker'),
  helpText('Visualize and manipulate your phone usage data.'),
  sidebarPanel(
    # uiOutput('welcome'),
    checkboxGroupInput('sampleFiles',
                       label = 'Check the box below to use sample data:',
                       choices = c(
                         # "Sample 1: from 05/11/20 to 17/07/21 
                         # (large - may take several seconds to load)" =
                         #   "data/StayFree Export - Total Usage - SAMPLE 1.xlsx",
                         "Sample: from 07-01-2021 to 22-08-2021" =
                           "data/StayFree Export - Total Usage - SAMPLE.xlsx"),
                       selected = c("data/StayFree Export - Total Usage - SAMPLE.xlsx")),
    uiOutput('files'),
    uiOutput('numApps'),
    uiOutput('dateRange')
    ),

  mainPanel(
    # uiOutput('main')
    tabsetPanel(
      # plotOutput('plot1'),
      tabPanel("Daily Usage", plotOutput('plot4')),
      tabPanel("Usage by Day of Week", plotOutput('plot3')),
      tabPanel("Usage by Application", plotOutput('plot2')),
      tabPanel("Advanced",
               plotOutput('pca'),
               p("Note that the interpretation of the two axes in the biplot may
                 be subective, and depend on the user's phone usage trends.
                 For example, a possible interpretation for the sample data's
                 axes are: apps used while commuting (e.g. Maps) vs. apps
                 used while stationary (e.g. Facebook, YouTube) for the x-axis,
                 and apps used in the middle of the week (e.g. Messages, Clock)
                 vs. apps used around the weekend (e.g. YouTube) for the y-axis."),
               plotOutput('contrib')),
    tabPanel("Help", icon=icon("question-circle"),
             strong("How To Use This App"),
             p("ScreenTime Tracker lets you track your screen time usage on your phone with
             interactive visualizations of your usage data generated by the ",
             a("StayFree mobile app",
               href="https://play.google.com/store/apps/details?id=com.burockgames.timeclocker",
               target="_blank"),". Try out the sample data,
               or follow the steps below to visualize your own phone usage:"),
             tags$ol(
               tags$li("Download ",
                       a("StayFree",
                         href="https://play.google.com/store/apps/details?id=com.burockgames.timeclocker",
                         target="_blank"), 
               " for free from Google Play (this app is only available on Android devices)."),
               tags$li('Export your StayFree phone data to an Excel file.'),
               tags$li('Drop your exported file(s) into the \"StayFree Export Usage File\"
                        section on the left sidebar of this page.')),
             p("For more information on this app, including the source code and sample data, visit the ", 
               a("GitHub repository",
               href = "https://github.com/a-a-lohn/screentime-tracker", target="_blank"), ".")
             )
    )
  )
)
