library(shiny)

fluidPage(
  includeCSS("www/styles.css"),
  titlePanel('ScreenTime Tracker', windowTitle = 'ScreenTime Tracker'),
  helpText('Visualize and manipulate your phone usage data.'),
  sidebarPanel(
    # uiOutput('welcome'),
    checkboxGroupInput('sampleFiles',
                       label = 'Check one or both of the boxes below to use sample data:',
                       choices = c(
                         "Sample 1: from 05/11/20 to 17/07/21 
                         (large - may take several seconds to load)" =
                           "data/StayFree Export - Total Usage - SAMPLE 1.xlsx",
                         "Sample 2: from 07/01/21 to 22/08/21 (small)" =
                           "data/StayFree Export - Total Usage - SAMPLE 2.xlsx"),
                       selected = c("data/StayFree Export - Total Usage - SAMPLE 1.xlsx")),
    uiOutput('files'),
    uiOutput('numApps'),
    uiOutput('dateRange')
    ),

  mainPanel(
    # uiOutput('main')
    tabsetPanel(
      # plotOutput('plot1'),
      tabPanel("Daily Usage", plotOutput('plot4')),
      tabPanel("Usage by Day of Week", plotOutput('plot3')),
      tabPanel("Usage by Application", plotOutput('plot2')),
      tabPanel("Advanced",
               plotOutput('pca'),
               plotOutput('contrib')),
    tabPanel("Help", icon=icon("question-circle"),
             strong("How To Use This App"),
             p("ScreenTime Tracker lets you track your screen time usage on your phone with
             interactive visualizations of your usage data generated by the ",
             a("StayFree mobile app",
               href="https://play.google.com/store/apps/details?id=com.burockgames.timeclocker",
               target="_blank"),". Try out the sample data,
               or follow the steps below to visualize your own phone usage:"),
             tags$ol(
               tags$li("Download ",
                       a("StayFree",
                         href="https://play.google.com/store/apps/details?id=com.burockgames.timeclocker",
                         target="_blank"), 
               " for free from Google Play (this app is only available on Android devices)."),
               tags$li('Export your StayFree phone data to an Excel file.'),
               tags$li('Drop your exported file(s) into the \"StayFree Export Usage File\"
                        section on the left sidebar of this page.')),
             p("For more information on this app, including the source code and sample data, visit the ", 
               a("GitHub repository",
               href = "https://github.com/a-a-lohn/screentime-tracker", target="_blank"), ".")
             )
    )
  )
)
